package com.deenislam.sdk.utils

const val BASE_AUTH_API_URL = "https://devapi.deenislamic.com/api/"
const val BASE_DEEN_SERVICE_API_URL = "https://devservices.deenislamic.com/api/"
const val BASE_CONTENT_URL = "http://27.131.15.12:801/contents/"
const val BASE_HADITH_API_URL = "https://api.sunnah.com/v1/"
const val BASE_HADITH_API_TEST_URL = "https://sunnah.com/ajax/"
const val BASE_QURAN_API_URL = "https://api.quran.com/api/v4/"
const val BASE_CONTENT_URL_SGP = "https://islamic-content.sgp1.digitaloceanspaces.com/"
const val BASE_QURAN_VERSE_AUDIO_URL = "https://verses.quran.com/"
const val PRIVACY_URL = "https://docs.google.com/document/d/150eDuTEfEEAT4YieKL31RZj8hHjFsN2WDgl-wDhvFEs/edit?usp=sharing"
const val TERMS_URL = "https://docs.google.com/document/d/1CY2LDWQpQMLDQUaE7G5umfXrVDC0cA2aaiLZpYWyoPI/edit"
const val MENU_HAJJ_AND_UMRAH = "HajjUmrah"
const val MENU_PRAYER_TIME= "prayerTime"
const val MENU_AL_QURAN = "ALQuran"
const val MENU_HADITH = "Hadith"
const val MENU_RAMADAN= "Ramadan"
const val MENU_INSPIRATION = "Inspiration"
const val MENU_DUA = "Dua"
const val MENU_LEARNING = "Learning"
const val MENU_ISLAMIC_GOODS = "IslamicGoods"
const val MENU_ISALIC_CONTENT = "IslamicContent"
const val MENU_ISLAMIC_LIFESTYLE = "IslamicLifestyle"
const val MENU_DONATION = "Donation"
const val MENU_99_NAME_OF_ALLAH = "99NameOfAllah"
const val MENU_ZAKAT = "Zakat"
const val MENU_DIGITAL_TASBEEH = "DigitalTasbeeh"
const val MENU_QIBLA_COMPASS = "QiblaCompass"
const val MENU_NEAREST_MOSQUE = "NearestMosque"
const val MENU_HAJJ = "Hajj"
const val MENU_QURAN_CLASS = "QuranClass"
const val MENU_PODCAST = "Podcast"
const val MENU_HAJJ_PACKAGE = "HajjPackage"
const val MENU_PRAYER_LEARNING = "PrayerLearning"
const val MENU_EID = "Eid"
const val MENU_ISLAMIC_CALENDAR = "IslamicCalendar"
const val MENU_LIVE_VIDEO = "Live Video"
const val MENU_ISLAMIC_JIGGASA = "IslamicJiggasa"
const val MENU_AZAN = "Azan"
const val MENU_ISLAMIC_EVENT = "IslamicEvent"
const val MENU_ISLAMIC_NAME = "IslamicName"

// :notifications-api
const val ACTION_START_ALARM_LOOPER = "alarm.loopers.START"
// makkah location
const val MAKKAH_LATITUDE = 21.4204009
const val MAKKAH_LONGITUDE = 39.8257354

