package com.deenislam.sdk.utils

const val BASE_AUTH_API_URL = "https://api.deenislamic.com/api/"
const val BASE_DEEN_SERVICE_API_URL = "https://services.deenislamic.com/api/"
const val BASE_QURAN_SHIKKHA_API_URL = "https://api.quranshikkha.app/api/v2/"
const val BASE_PAYMENT_API_URL = "https://payment.islamicservice.net/"
const val NAGAD_BASE_PAYMENT_API_URL = "https://nagadpayment.islamicservice.net/api/"
const val BASE_CONTENT_URL = "http://27.131.15.12:801/contents/"
const val BASE_HADITH_API_URL = "https://api.sunnah.com/v1/"
const val BASE_HADITH_API_TEST_URL = "https://sunnah.com/ajax/"
const val BASE_QURAN_API_URL = "https://api.qurancdn.com/api/v4/"
const val BASE_YOUTUBE_VIDEO_API = "https://www.youtube.com/youtubei/v1/"
const val YOUTUBE_VIDEO_KEY="STEHLGCilw_Y9_11qcW8AIzaSyAO_FJ2SlqU8Q4"
    //"https://api.quran.com/api/v4/"
const val BASE_CONTENT_URL_SGP = "https://islamic-content.sgp1.digitaloceanspaces.com/"
const val BASE_QURAN_VERSE_AUDIO_URL = "https://verses.quran.com/"

const val PRIVACY_URL = "https://deenislamic.com/privacy_policy.html"
const val DIGITAL_QURAN_CLASS_TC = "https://docs.google.com/document/d/1ghdRU9Qva5vuNXIMak1D4R7EEnLWhUje4ohJFb8LgO0/edit?usp=sharing"
const val QURAN_SHIKKHA_PAYMENT_TC = "https://docs.google.com/document/d/1UNKbtp7f1uzpeqQZsCYLSdNEpjVpp9A0vlE9qZwTBqU/edit?usp=sharing"
const val TERMS_URL = "https://www.docs.google.com/document/d/129QQoNcPiCMgfr2G6MBbjKal74JOYFro_hcwrnajFuU/edit?usp=sharing"

const val MENU_HAJJ_AND_UMRAH = "HajjUmrah"
const val MENU_PRAYER_TIME= "prayerTime"
const val MENU_AL_QURAN = "ALQuran"
const val MENU_HADITH = "Hadith"
const val MENU_RAMADAN_OTHER_DAY= "RamadanOtherDay"
const val MENU_RAMADAN= "RamadanRegular"
const val MENU_INSPIRATION = "Inspiration"
const val MENU_DUA = "Dua"
const val MENU_LEARNING = "Learning"
const val MENU_ISLAMIC_GOODS = "IslamicGoods"
const val MENU_ISALIC_CONTENT = "IslamicContent"
const val MENU_ISLAMIC_LIFESTYLE = "IslamicLifestyle"
const val MENU_DONATION = "Donation"
const val MENU_99_NAME_OF_ALLAH = "99NameOfAllah"
const val MENU_ZAKAT = "Zakat"
const val MENU_DIGITAL_TASBEEH = "DigitalTasbeeh"
const val MENU_QIBLA_COMPASS = "QiblaCompass"
const val MENU_NEAREST_MOSQUE = "NearestMosque"
const val MENU_LIVE_PODCAST = "LivePodcast"
const val MENU_ISLAMIC_EDUCATION_VIDEO = "IslamicEducationStory"
const val MENU_LIVE_MAKKAH_MADINA = "LiveMakkahMadina"
const val MENU_HAJJ = "Hajj"
const val MENU_IJTEMA = "ijtema"
const val MENU_QURAN_CLASS = "QuranClass"
const val MENU_PODCAST = "Podcast"
const val MENU_HAJJ_PACKAGE = "HajjPackage"
const val MENU_PRAYER_LEARNING = "PrayerLearning"
const val MENU_KHATAM_E_QURAN = "KhatamQuran"
const val MENU_EID = "Eid"
const val MENU_ISLAMIC_CALENDAR = "IslamicCalendar"
const val MENU_LIVE_VIDEO = "Live Video"
const val MENU_ISLAMIC_JIGGASA = "IslamicJiggasa"
const val MENU_AZAN = "Azan"
const val MENU_ISLAMIC_EVENT = "IslamicEvent"
const val MENU_ISLAMIC_NAME = "IslamicName"
const val HAJJ_SUB_CAT = "HajjSubCat"
const val HAJJ_GUIDE = "HajjGuide"
const val RECYCLER_DATA_AVAILABLE = 1
const val RECYCLERFOOTER = 2
const val RequestBodyMediaType = "application/json"

// :notifications-api
const val ACTION_START_ALARM_LOOPER = "alarm.loopers.START"
// makkah location
const val MAKKAH_LATITUDE = 21.4204009
const val MAKKAH_LONGITUDE = 39.8257354
const val COURSE_SLUG_QURAN_ACADEMY = "al-quran-course"
const val QURAN_ACADEMY_GAKK_API_KEY = "AFe3P41zmOw6gS0UVqw2Q216kFuJYo9t4xt0x6Ph"
const val PRODUCT_ID_QURAN_CLASS_350_TK = "quran_class_350_tk"
const val PRODUCT_ID_QURAN_CLASS_450_TK = "quran_class_450_tk"
const val PATCH_COMMON_CARD_LIST = "CommonCardList"
const val PATCH_MEDIUM_CARD_LIST = "MediumCardList"
